### ISSUE TITLE
Function call with too few arguments

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#14]
Could not find a trailer file URL with resolution '1080'. Retrying with '720'
    Traceback (most recent call last):
      File "apple_trailer_downloader/download_trailers.py", line 506, in <module>
        settings['video_types']
      File "apple_trailer_downloader/download_trailers.py", line 243, in downloadTrailersFromPage
        trailerUrls = getTrailerFileUrls(pageUrl, res, types)
      File "apple_trailer_downloader/download_trailers.py", line 48, in getTrailerFileUrls
        urls = getITunesTrailersFileUrls(pageUrl, res, types)
      File "apple_trailer_downloader/download_trailers.py", line 74, in getITunesTrailersFileUrls
        return getITunesTrailersFileUrls(pageUrl, '720')
    TypeError: getITunesTrailersFileUrls() takes exactly 3 arguments (2 given)

**Comment by aag** [comment]
This has been fixed in the newest version.
