### ISSUE TITLE
traceback error...

### ISSUE THREAD

**Issue by ITguy3118** [aag/apple_trailer_downloader#23]
It was recommended to me to use this as a workaround for getting apple trailers to work with CinemaVision. I've only put this script on my machine and used the default config. I observed it downloading 13 trailers and then this traceback happened. If i run the script again It will check the existing files, then produce the same traceback and does non continue

```
Traceback (most recent call last):
  File "C:\Users\Andrew Sutcliffe\Downloads\trailerdownloader\download_trailers.py", line 599, in <module>
    main()
  File "C:\Users\Andrew Sutcliffe\Downloads\trailerdownloader\download_trailers.py", line 595, in main
    download_trailers_from_page(url, settings)
  File "C:\Users\Andrew Sutcliffe\Downloads\trailerdownloader\download_trailers.py", line 278, in download_trailers_from_page
    settings['video_types'])
  File "C:\Users\Andrew Sutcliffe\Downloads\trailerdownloader\download_trailers.py", line 194, in file_already_downloaded
    trailer_prefix = '{}.trailer'.format(clean_title.lower())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 6: ordinal not in range(128)
```

I deleted everything and started again and it fails in the same place each time, this trailer seems to be causing an issue 

https://trailers.apple.com/trailers/independent/ronnies/

How to proceed?

**Comment by aag** [comment]
Thanks for reporting this bug. I've just published a new release with a fix for this issue. Please update your version of the script and try again.

**Comment by aag** [comment]
Since I haven't heard back, I'm assuming this issue is fixed, so I'm closing it.
